# Generated by Django 4.1.5 on 2023-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=20)),
                ('titile', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=500)),
                ('cost', models.IntegerField(max_length=5)),
                ('offered_by', models.CharField(max_length=200)),
                ('course_pic', models.ImageField(upload_to='course_image')),
            ],
        ),
    ]
