# Generated by Django 4.1.5 on 2023-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
    ]
